import React, { ReactNode, useState } from "react";
import Head from "next/head";
import SideBar from "./components/SideBar";
import { useRouter } from "next/router";
import Navbar from "./components/NavBar/index";

type Props = {
  children: ReactNode;
};

const index = ({ children }: Props) => {
  const [open, setOpen] = useState<Boolean>(true);
  const { pathname } = useRouter();
  const isDashboard = pathname.includes("/dashboard" || "/analytics");

  return (
    <>
      <Head>
        <title>BT Finance Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex w-full bg-white">
        {isDashboard ? (
          <>
            <SideBar open={open} setOpen={setOpen} />
          </>
        ) : null}
        <div
          className={`flex flex-col justify-start items-start ${
            isDashboard
              ? " tabletMd:pl-60 mobileLg:pl-24 pl-0"
              : "tabletMd:pl-0 mobileLg:pl-0 pl-0"
          }
         
           w-full`}
        >
          <div
            className={`flex flex-col ${
              isDashboard ? "mobileLg:items-end" : "mobileLg:items-start"
            } items-start w-full`}
          >
            {isDashboard ? (
              <>
                <Navbar open={open} setOpen={setOpen} />
              </>
            ) : (
              <></>
            )}

            {children}
          </div>
        </div>
      </div>
    </>
  );
};

export default index;
