import Head from "next/head";
import { Inter } from "next/font/google";
import React, { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [open, setOpen] = useState<Boolean>(true);
  return (
    <>
      <Head>
        <title>BT Finance Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="p-7 text-2xl font-semibold flex-1 h-screen ">
          <h1 className="bg-green-600">Home Page</h1>
        </div>
      </main>
    </>
  );
}
