import React from "react";
import Head from "next/head";
import Dashboard from "../../components/Dashboard/index";
type Props = {};

const index = (props: Props) => {
  return (
    <>
      <Head>
        <title>BT Finance Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="mobileLg:p-7  p-0 text-2xl font-semibold flex-1 h-screen w-full ">
        <Dashboard />
      </div>
    </>
  );
};

export default index;
